class InternetEndpoints:
    BAF                         = "internet/accesos/baf"
    BAF_PROVINCIA               = "internet/accesos/baf/provincias"
    ACCESOS_PROVINCIA           = "internet/accesos/provincia"
    ACCESOS_LOCALIDAD           = "internet/accesos/localidad"
    TECNOLOGIAS                 = "internet/accesos/tecnologias"
    TECNOLOGIAS_PROVINCIA       = "internet/accesos/tecnologias/provincias"
    TECNOLOGIAS_LOCALIDAD       = "internet/accesos/tecnologias/localidades"
    VELOCIDAD_RANGOS            = "internet/accesos/rangos-velocidad"
    VELOCIDAD_RANGOS_PROVINCIA  = "internet/accesos/rangos-velocidad/provincias"
    PENETRACION                 = "internet/penetracion"
    PENETRACION_PROVINCIA       = "internet/penetracion/provincias"
    VELOCIDAD_MEDIA             = "internet/accesos/velocidad-media"
    VELOCIDAD_MEDIA_PROVINCIA   = "internet/accesos/velocidad-media/provincias"
    VELOCIDAD_PROVINCIA         = "internet/accesos/velocidad/provincia"
    VELOCIDAD_LOCALIDAD         = "internet/accesos/velocidad/localidades"
    INGRESOS                    = "internet/ingresos"
